"""empty message

Revision ID: 0efd33a59d88
Revises: ce49d0d897ab
Create Date: 2020-04-14 17:46:58.778213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0efd33a59d88'
down_revision = 'ce49d0d897ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('package', 'token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('token', 'token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'token',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('package', 'token',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    op.alter_column('node', 'uuid',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
