"""empty message

Revision ID: 24e4e7faf72d
Revises: deec9ce7637c
Create Date: 2020-05-29 12:59:56.985732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e4e7faf72d'
down_revision = 'deec9ce7637c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_column('package', 'manager_id')
    # ### end Alembic commands ###
