"""empty message

Revision ID: 8415cda51a97
Revises: 0efd33a59d88
Create Date: 2020-05-04 05:46:34.930776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8415cda51a97'
down_revision = '0efd33a59d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('_path', sa.Text(), nullable=True))
    op.add_column('package', sa.Column('progress', sa.Integer(), nullable=True))
    op.drop_constraint('package_ibfk_2', 'package', type_='foreignkey')
    op.drop_constraint('package_ibfk_1', 'package', type_='foreignkey')
    op.drop_column('package', 'current_node_id')
    op.drop_column('package', 'next_node_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('next_node_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('package', sa.Column('current_node_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('package_ibfk_1', 'package', 'node', ['current_node_id'], ['id'])
    op.create_foreign_key('package_ibfk_2', 'package', 'node', ['next_node_id'], ['id'])
    op.drop_column('package', 'progress')
    op.drop_column('package', '_path')
    # ### end Alembic commands ###
