"""empty message

Revision ID: bc46d4e2c280
Revises: 24e4e7faf72d
Create Date: 2020-05-29 13:23:47.514269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc46d4e2c280'
down_revision = '24e4e7faf72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('realname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'realname')
    # ### end Alembic commands ###
