"""empty message

Revision ID: ce49d0d897ab
Revises: 8c75d10a4264
Create Date: 2020-04-12 15:07:35.705714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce49d0d897ab'
down_revision = '8c75d10a4264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('courier_id', sa.Integer(), nullable=True))
    op.add_column('package', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('package', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('package', sa.Column('token', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'package', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'package', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'package', 'user', ['courier_id'], ['id'])
    op.add_column('user', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('open_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'open_id')
    op.drop_column('user', 'address')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_column('package', 'token')
    op.drop_column('package', 'sender_id')
    op.drop_column('package', 'receiver_id')
    op.drop_column('package', 'courier_id')
    # ### end Alembic commands ###
